project_name             = "ecommerce-platform"
environment              = "dev"
aws_region               = "ap-south-1"
vpc_cidr                 = "10.0.0.0/16"
public_subnet_cidrs      = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs     = ["10.0.101.0/24", "10.0.102.0/24"]
eks_cluster_version      = "1.30"
node_group_instance_type = "t3.micro"
desired_size             = 2
max_size                 = 3
min_size                 = 1
ecr_repository_name      = "ecommerce-platform"
